import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/server';
import { loadSchedule } from '@/lib/schedule/load';
import { icsResponse } from '@/lib/ics/response';
import { siteUrl } from '@/lib/http';
import { logger } from '@/lib/logger';
import { consumeRateLimit } from '@/lib/quota';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * The subscribable calendar feed.
 *
 * Authenticated by an unguessable 48-hex-character token in the path rather
 * than a session, because calendar clients cannot log in. That makes the URL
 * itself the credential, so:
 *   - the token is CSPRNG-generated by Postgres and rotatable by the student,
 *   - responses are never cached by an intermediary,
 *   - a wrong token gets a flat 404 with no hint that the shape was close,
 *   - and lookups are rate-limited so the space cannot be walked.
 *
 * This route is deliberately excluded from auth middleware.
 */

const TOKEN_PATTERN = /^[0-9a-f]{48}$/;

export async function GET(
  request: Request,
  { params }: { params: Promise<{ token: string }> },
): Promise<NextResponse> {
  const { token: raw } = await params;
  const token = raw.replace(/\.ics$/i, '').toLowerCase();

  const notFound = () =>
    new NextResponse('Not found', { status: 404, headers: { 'Cache-Control': 'no-store' } });

  if (!TOKEN_PATTERN.test(token)) return notFound();

  // Bound how fast the token space can be probed, per token prefix.
  const withinLimit = await consumeRateLimit(`feed:${token.slice(0, 12)}`, 120, 3600);
  if (!withinLimit) {
    return new NextResponse('Too many requests', {
      status: 429,
      headers: { 'Cache-Control': 'no-store', 'Retry-After': '3600' },
    });
  }

  // The token is the credential, so this necessarily runs as the service role.
  const supabase = createAdminClient();
  const { data: user } = await supabase
    .from('users')
    .select('id')
    .eq('feed_token', token)
    .maybeSingle();

  if (!user) return notFound();

  const payload = await loadSchedule(supabase, null, user.id);
  if (!payload) {
    // A valid token with no schedule yet: an empty calendar, not an error.
    // Calendar clients retry a 404 far less politely than they poll an empty feed.
    return icsResponse(
      { term: { id: '', name: 'Coursework', timezone: 'UTC', startDate: null, endDate: null }, courses: [], items: [] },
      { feedUrl: `${siteUrl()}/api/feed/${token}.ics` },
    );
  }

  logger.info('feed.served', { userId: user.id, items: payload.items.length });
  return icsResponse(payload, { feedUrl: `${siteUrl()}/api/feed/${token}.ics` });
}
